// Compose service 확장 필드 정의를 관리합니다.
// 후속 작업에서는 이 목록에 field definition을 추가하는 방식으로 확장합니다.
export const COMPOSE_SERVICE_FIELD_DEFINITIONS = [
  {
    key: "command",
    yamlKey: "command",
    label: "Command",
    description: "컨테이너 시작 시 실행할 명령입니다.",
    category: "execution",
    type: "text",
    placeholder: "npm run dev",
  },
  {
    key: "entrypoint",
    yamlKey: "entrypoint",
    label: "Entrypoint",
    description: "컨테이너 기본 entrypoint를 재정의합니다.",
    category: "execution",
    type: "text",
    placeholder: "/docker-entrypoint.sh",
  },
  {
    key: "workingDir",
    yamlKey: "working_dir",
    label: "Working Directory",
    description: "컨테이너 내부 작업 디렉터리입니다.",
    category: "execution",
    type: "text",
    placeholder: "/app",
  },
  {
    key: "user",
    yamlKey: "user",
    label: "User",
    description: "컨테이너 프로세스를 실행할 사용자입니다.",
    category: "execution",
    type: "text",
    placeholder: "node",
  },
  {
    key: "envFile",
    yamlKey: "env_file",
    label: "Env File",
    description: "환경변수 파일 경로 목록입니다.",
    category: "execution",
    type: "list",
    placeholder: ".env",
  },
  {
    key: "restart",
    yamlKey: "restart",
    label: "Restart Policy",
    description: "컨테이너 종료 시 재시작 정책입니다.",
    category: "lifecycle",
    type: "select",
    options: [
      { label: "선택 안 함", value: "" },
      { label: "no", value: "no" },
      { label: "always", value: "always" },
      { label: "on-failure", value: "on-failure" },
      { label: "unless-stopped", value: "unless-stopped" },
    ],
  },
  {
    key: "build",
    yamlKey: "build",
    label: "Build",
    description: "이미지를 빌드할 기본 context 경로입니다.",
    category: "build",
    type: "object",
    fields: [
      {
        key: "context",
        yamlKey: "context",
        label: "Context",
        type: "text",
        placeholder: "./frontend",
      },
    ],
  },
  {
    key: "hostname",
    yamlKey: "hostname",
    label: "Hostname",
    description: "컨테이너 내부에서 사용할 hostname입니다.",
    category: "network",
    type: "text",
    placeholder: "frontend-host",
  },
  {
    key: "tmpfs",
    yamlKey: "tmpfs",
    label: "Tmpfs",
    description: "tmpfs로 마운트할 경로 목록입니다.",
    category: "storage",
    type: "list",
    placeholder: "/tmp",
  },
  {
    key: "cpus",
    yamlKey: "cpus",
    label: "CPUs",
    description: "컨테이너가 사용할 CPU 제한 값입니다.",
    category: "resource",
    type: "text",
    placeholder: "0.5",
  },
  {
    key: "privileged",
    yamlKey: "privileged",
    label: "Privileged",
    description: "컨테이너를 privileged 모드로 실행합니다.",
    category: "security",
    type: "boolean",
  },
  {
    key: "profiles",
    yamlKey: "profiles",
    label: "Profiles",
    description: "Compose profile 이름 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "dev",
  },
]

export function getComposeFieldsByCategory(categoryId) {
  return COMPOSE_SERVICE_FIELD_DEFINITIONS.filter((field) => {
    return field.category === categoryId
  })
}