// 빌드 설정 카테고리의 Compose service field definition을 관리합니다.
export const buildFields = [
  {
    key: "build",
    yamlKey: "build",
    label: "Build",
    description: "이미지 빌드 설정입니다.",
    category: "build",
    type: "object",
    fields: [
      {
        key: "context",
        yamlKey: "context",
        label: "Context",
        description: "이미지를 빌드할 기본 context 경로입니다.",
        type: "text",
        placeholder: "./frontend",
      },
      {
        key: "dockerfile",
        yamlKey: "dockerfile",
        label: "Dockerfile",
        description: "context 기준으로 사용할 Dockerfile 경로입니다.",
        type: "text",
        placeholder: "Dockerfile.dev",
      },
      {
        key: "args",
        yamlKey: "args",
        label: "Build Args",
        description:
          "빌드 시 전달할 build argument 목록입니다.",
        type: "list",
        placeholder: "NODE_ENV=development",
      },
      {
        key: "target",
        yamlKey: "target",
        label: "Target",
        description: "멀티스테이지 빌드에서 사용할 target stage입니다.",
        type: "text",
        placeholder: "dev",
      },
      {
        key: "noCache",
        yamlKey: "no_cache",
        label: "No Cache",
        description: "이미지 빌드 시 cache를 사용하지 않습니다.",
        type: "boolean",
      },
      {
        key: "pull",
        yamlKey: "pull",
        label: "Pull",
        description: "빌드 전에 base image pull을 시도합니다.",
        type: "boolean",
      },
      {
        key: "network",
        yamlKey: "network",
        label: "Network",
        description: "빌드 과정에서 사용할 network 모드입니다.",
        type: "text",
        placeholder: "host",
      },
      {
        key: "shmSize",
        yamlKey: "shm_size",
        label: "SHM Size",
        description: "빌드 컨테이너의 /dev/shm 크기입니다.",
        type: "text",
        placeholder: "64m",
      },
      {
        key: "extraHosts",
        yamlKey: "extra_hosts",
        label: "Extra Hosts",
        description: "빌드 컨테이너 hosts 파일에 추가할 host mapping 목록입니다.",
        type: "list",
        placeholder: "host.docker.internal:host-gateway",
      },
      {
        key: "platforms",
        yamlKey: "platforms",
        label: "Platforms",
        description: "빌드 대상 platform 목록입니다.",
        type: "list",
        placeholder: "linux/amd64",
      },
      {
        key: "tags",
        yamlKey: "tags",
        label: "Tags",
        description: "빌드 결과 이미지에 추가할 tag 목록입니다.",
        type: "list",
        placeholder: "my-frontend:dev",
      },
    ],
  },
]