// 컨테이너 동작 설정 카테고리의 Compose service field definition을 관리합니다.
export const lifecycleFields = [
  {
    key: "restart",
    yamlKey: "restart",
    label: "Restart Policy",
    description: "컨테이너 종료 시 재시작 정책입니다.",
    category: "lifecycle",
    type: "select",
    options: [
      { label: "선택 안 함", value: "" },
      { label: "no", value: "no" },
      { label: "always", value: "always" },
      { label: "on-failure", value: "on-failure" },
      { label: "unless-stopped", value: "unless-stopped" },
    ],
  },
  {
    key: "attach",
    yamlKey: "attach",
    label: "Attach",
    description: "Compose 실행 시 service 로그를 연결할지 설정합니다.",
    category: "lifecycle",
    type: "boolean",
  },
  {
    key: "init",
    yamlKey: "init",
    label: "Init",
    description: "컨테이너 안에서 init 프로세스를 실행합니다.",
    category: "lifecycle",
    type: "boolean",
  },
  {
    key: "tty",
    yamlKey: "tty",
    label: "TTY",
    description: "컨테이너에 TTY를 할당합니다.",
    category: "lifecycle",
    type: "boolean",
  },
  {
    key: "stdinOpen",
    yamlKey: "stdin_open",
    label: "Stdin Open",
    description: "표준 입력을 열린 상태로 유지합니다.",
    category: "lifecycle",
    type: "boolean",
  },
  {
    key: "readOnly",
    yamlKey: "read_only",
    label: "Read Only",
    description: "컨테이너 파일 시스템을 읽기 전용으로 실행합니다.",
    category: "lifecycle",
    type: "boolean",
  },
  {
    key: "stopSignal",
    yamlKey: "stop_signal",
    label: "Stop Signal",
    description: "컨테이너 종료 시 보낼 signal입니다.",
    category: "lifecycle",
    type: "text",
    placeholder: "SIGTERM",
  },
  {
    key: "stopGracePeriod",
    yamlKey: "stop_grace_period",
    label: "Stop Grace Period",
    description: "컨테이너 종료 전 대기 시간입니다.",
    category: "lifecycle",
    type: "text",
    placeholder: "30s",
  },
  {
    key: "pullPolicy",
    yamlKey: "pull_policy",
    label: "Pull Policy",
    description: "이미지를 pull할지 결정하는 정책입니다.",
    category: "lifecycle",
    type: "select",
    options: [
      { label: "선택 안 함", value: "" },
      { label: "always", value: "always" },
      { label: "never", value: "never" },
      { label: "missing", value: "missing" },
      { label: "build", value: "build" },
    ],
  },
]