// 네트워크 설정 카테고리의 Compose service field definition을 관리합니다.
export const networkFields = [
  {
    key: "hostname",
    yamlKey: "hostname",
    label: "Hostname",
    description: "컨테이너 내부에서 사용할 hostname입니다.",
    category: "network",
    type: "text",
    placeholder: "frontend-host",
  },
  {
    key: "domainname",
    yamlKey: "domainname",
    label: "Domain Name",
    description: "컨테이너에 설정할 domain name입니다.",
    category: "network",
    type: "text",
    placeholder: "example.local",
  },
  {
    key: "expose",
    yamlKey: "expose",
    label: "Expose",
    description: "호스트에 publish하지 않고 다른 service에 노출할 포트 목록입니다.",
    category: "network",
    type: "list",
    placeholder: "3000",
  },
  {
    key: "dns",
    yamlKey: "dns",
    label: "DNS",
    description: "컨테이너에서 사용할 DNS 서버 목록입니다.",
    category: "network",
    type: "list",
    placeholder: "8.8.8.8",
  },
  {
    key: "dnsOpt",
    yamlKey: "dns_opt",
    label: "DNS Options",
    description: "컨테이너 DNS resolver 옵션 목록입니다.",
    category: "network",
    type: "list",
    placeholder: "use-vc",
  },
  {
    key: "dnsSearch",
    yamlKey: "dns_search",
    label: "DNS Search",
    description: "컨테이너 DNS search domain 목록입니다.",
    category: "network",
    type: "list",
    placeholder: "example.local",
  },
  {
    key: "extraHosts",
    yamlKey: "extra_hosts",
    label: "Extra Hosts",
    description: "컨테이너 hosts 파일에 추가할 host mapping 목록입니다.",
    category: "network",
    type: "list",
    placeholder: "host.docker.internal:host-gateway",
  },
  {
    key: "networkMode",
    yamlKey: "network_mode",
    label: "Network Mode",
    description: "컨테이너 네트워크 모드를 지정합니다.",
    category: "network",
    type: "text",
    placeholder: "bridge",
  },
  {
    key: "macAddress",
    yamlKey: "mac_address",
    label: "MAC Address",
    description: "컨테이너에 지정할 MAC address입니다.",
    category: "network",
    type: "text",
    placeholder: "02:42:ac:11:00:02",
  },
]