// 서비스 관계/운영/배포 설정 카테고리의 Compose service field definition을 관리합니다.
export const operationFields = [
  {
    key: "dependsOn",
    yamlKey: "depends_on",
    label: "Depends On",
    description:
      "현재 service가 의존하는 service 이름 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "backend",
  },
  {
    key: "extends",
    yamlKey: "extends",
    label: "Extends",
    description:
      "다른 Compose service 설정을 확장합니다.",
    category: "operation",
    type: "object",
    fields: [
      {
        key: "file",
        yamlKey: "file",
        label: "File",
        description: "확장할 service가 정의된 Compose 파일 경로입니다.",
        type: "text",
        placeholder: "common.yml",
      },
      {
        key: "service",
        yamlKey: "service",
        label: "Service",
        description: "확장할 service 이름입니다.",
        type: "text",
        placeholder: "webapp",
      },
    ],
  },
  {
    key: "networks",
    yamlKey: "networks",
    label: "Networks",
    description:
      "service가 참여할 network 이름 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "app-network",
  },
  {
    key: "platform",
    yamlKey: "platform",
    label: "Platform",
    description: "service image/build에 사용할 대상 플랫폼입니다.",
    category: "operation",
    type: "text",
    placeholder: "linux/amd64",
  },
  {
    key: "models",
    yamlKey: "models",
    label: "Models",
    description:
      "service가 런타임에 사용할 model 이름 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "my_model",
  },
  {
    key: "provider",
    yamlKey: "provider",
    label: "Provider",
    description:
      "Compose가 직접 관리하지 않는 외부 provider service 설정입니다.",
    category: "operation",
    type: "object",
    fields: [
      {
        key: "type",
        yamlKey: "type",
        label: "Type",
        description: "service lifecycle을 위임할 provider type입니다.",
        type: "text",
        placeholder: "awesomecloud",
      },
    ],
  },
  {
    key: "profiles",
    yamlKey: "profiles",
    label: "Profiles",
    description: "Compose profile 이름 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "dev",
  },
  {
    key: "labels",
    yamlKey: "labels",
    label: "Labels",
    description:
      "컨테이너에 추가할 label 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "com.example.description=frontend",
  },
  {
    key: "labelFile",
    yamlKey: "label_file",
    label: "Label File",
    description: "label을 불러올 파일 경로 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "./labels.env",
  },
  {
    key: "annotations",
    yamlKey: "annotations",
    label: "Annotations",
    description:
      "service에 추가할 annotation 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "com.example.owner=team-a",
  },
  {
    key: "links",
    yamlKey: "links",
    label: "Links",
    description: "다른 service와 연결할 link 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "backend",
  },
  {
    key: "externalLinks",
    yamlKey: "external_links",
    label: "External Links",
    description: "Compose 외부 container/service link 목록입니다.",
    category: "operation",
    type: "list",
    placeholder: "redis",
  },
  {
    key: "healthcheck",
    yamlKey: "healthcheck",
    label: "Healthcheck",
    description:
      "컨테이너 상태 확인 설정입니다.",
    category: "operation",
    type: "object",
    fields: [
      {
        key: "test",
        yamlKey: "test",
        label: "Test",
        description:
          "healthcheck 실행 명령입니다. CMD, curl, -f, URL처럼 항목을 나누어 입력합니다.",
        type: "list",
        placeholder: "CMD",
      },
      {
        key: "interval",
        yamlKey: "interval",
        label: "Interval",
        description: "healthcheck 실행 간격입니다.",
        type: "text",
        placeholder: "30s",
      },
      {
        key: "timeout",
        yamlKey: "timeout",
        label: "Timeout",
        description: "healthcheck timeout 값입니다.",
        type: "text",
        placeholder: "10s",
      },
      {
        key: "retries",
        yamlKey: "retries",
        label: "Retries",
        description: "healthcheck 재시도 횟수입니다.",
        type: "text",
        placeholder: "3",
      },
      {
        key: "startPeriod",
        yamlKey: "start_period",
        label: "Start Period",
        description: "컨테이너 시작 후 healthcheck 실패를 무시할 초기 시간입니다.",
        type: "text",
        placeholder: "40s",
      },
      {
        key: "disable",
        yamlKey: "disable",
        label: "Disable",
        description: "이미지에 정의된 healthcheck를 비활성화합니다.",
        type: "boolean",
      },
    ],
  },
  {
    key: "logging",
    yamlKey: "logging",
    label: "Logging",
    description:
      "컨테이너 logging driver 설정입니다.",
    category: "operation",
    type: "object",
    fields: [
      {
        key: "driver",
        yamlKey: "driver",
        label: "Driver",
        description: "logging driver 이름입니다.",
        type: "select",
        options: [
          { label: "선택 안 함", value: "" },
          { label: "json-file", value: "json-file" },
          { label: "local", value: "local" },
          { label: "none", value: "none" },
          { label: "syslog", value: "syslog" },
          { label: "journald", value: "journald" },
          { label: "gelf", value: "gelf" },
          { label: "fluentd", value: "fluentd" },
          { label: "awslogs", value: "awslogs" },
          { label: "splunk", value: "splunk" },
          { label: "etwlogs", value: "etwlogs" },
        ],
      },
      {
        key: "options",
        yamlKey: "options",
        label: "Options",
        description:
          "logging driver 옵션입니다.",
        type: "object",
        fields: [
          {
            key: "maxSize",
            yamlKey: "max-size",
            label: "Max Size",
            description: "json-file/local driver의 로그 파일 최대 크기입니다.",
            type: "text",
            placeholder: "10m",
          },
          {
            key: "maxFile",
            yamlKey: "max-file",
            label: "Max File",
            description: "보관할 로그 파일 개수입니다.",
            type: "text",
            placeholder: "3",
          },
          {
            key: "compress",
            yamlKey: "compress",
            label: "Compress",
            description: "local driver 로그 압축 여부입니다.",
            type: "text",
            placeholder: "true",
          },
        ],
      },
    ],
  },
  {
    key: "deploy",
    yamlKey: "deploy",
    label: "Deploy",
    description:
      "배포 관련 설정입니다.",
    category: "operation",
    type: "object",
    fields: [
      {
        key: "replicas",
        yamlKey: "replicas",
        label: "Replicas",
        description: "service replica 개수입니다.",
        type: "text",
        placeholder: "2",
      },
      {
        key: "mode",
        yamlKey: "mode",
        label: "Mode",
        description: "service 배포 모드입니다.",
        type: "select",
        options: [
          { label: "선택 안 함", value: "" },
          { label: "replicated", value: "replicated" },
          { label: "global", value: "global" },
        ],
      },
      {
        key: "restartPolicy",
        yamlKey: "restart_policy",
        label: "Restart Policy",
        description: "deploy 하위 restart policy 설정입니다.",
        type: "object",
        fields: [
          {
            key: "condition",
            yamlKey: "condition",
            label: "Condition",
            description: "재시작 조건입니다.",
            type: "select",
            options: [
              { label: "선택 안 함", value: "" },
              { label: "none", value: "none" },
              { label: "on-failure", value: "on-failure" },
              { label: "any", value: "any" },
            ],
          },
          {
            key: "delay",
            yamlKey: "delay",
            label: "Delay",
            description: "재시작 전 대기 시간입니다.",
            type: "text",
            placeholder: "5s",
          },
          {
            key: "maxAttempts",
            yamlKey: "max_attempts",
            label: "Max Attempts",
            description: "최대 재시도 횟수입니다.",
            type: "text",
            placeholder: "3",
          },
          {
            key: "window",
            yamlKey: "window",
            label: "Window",
            description: "재시도 판단 시간 창입니다.",
            type: "text",
            placeholder: "120s",
          },
        ],
      },
    ],
  },
  {
    key: "scale",
    yamlKey: "scale",
    label: "Scale",
    description: "service container 실행 개수입니다.",
    category: "operation",
    type: "text",
    placeholder: "2",
  },
]