// 리소스 설정 카테고리의 Compose service field definition을 관리합니다.
export const resourceFields = [
  {
    key: "cpus",
    yamlKey: "cpus",
    label: "CPUs",
    description: "컨테이너가 사용할 CPU 제한 값입니다.",
    category: "resource",
    type: "text",
    placeholder: "0.5",
  },
  {
    key: "cpuCount",
    yamlKey: "cpu_count",
    label: "CPU Count",
    description: "컨테이너가 사용할 CPU 개수입니다.",
    category: "resource",
    type: "text",
    placeholder: "2",
  },
  {
    key: "cpuPercent",
    yamlKey: "cpu_percent",
    label: "CPU Percent",
    description: "컨테이너가 사용할 CPU 비율입니다.",
    category: "resource",
    type: "text",
    placeholder: "50",
  },
  {
    key: "cpuShares",
    yamlKey: "cpu_shares",
    label: "CPU Shares",
    description: "다른 컨테이너와 비교한 상대적인 CPU 가중치입니다.",
    category: "resource",
    type: "text",
    placeholder: "512",
  },
  {
    key: "cpuPeriod",
    yamlKey: "cpu_period",
    label: "CPU Period",
    description: "CPU CFS period 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "100000",
  },
  {
    key: "cpuQuota",
    yamlKey: "cpu_quota",
    label: "CPU Quota",
    description: "CPU CFS quota 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "50000",
  },
  {
    key: "cpuRtRuntime",
    yamlKey: "cpu_rt_runtime",
    label: "CPU RT Runtime",
    description: "실시간 스케줄러용 CPU runtime 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "400ms",
  },
  {
    key: "cpuRtPeriod",
    yamlKey: "cpu_rt_period",
    label: "CPU RT Period",
    description: "실시간 스케줄러용 CPU period 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "1400us",
  },
  {
    key: "cpuset",
    yamlKey: "cpuset",
    label: "CPU Set",
    description: "컨테이너가 사용할 CPU 코어 범위를 지정합니다.",
    category: "resource",
    type: "text",
    placeholder: "0-1",
  },
  {
    key: "memLimit",
    yamlKey: "mem_limit",
    label: "Memory Limit",
    description: "컨테이너 메모리 제한 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "512m",
  },
  {
    key: "memReservation",
    yamlKey: "mem_reservation",
    label: "Memory Reservation",
    description: "컨테이너 메모리 soft limit 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "256m",
  },
  {
    key: "memSwappiness",
    yamlKey: "mem_swappiness",
    label: "Memory Swappiness",
    description: "컨테이너 메모리 swappiness 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "60",
  },
  {
    key: "memswapLimit",
    yamlKey: "memswap_limit",
    label: "Memory Swap Limit",
    description: "메모리와 swap을 포함한 전체 제한 값을 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "1g",
  },
  {
    key: "oomKillDisable",
    yamlKey: "oom_kill_disable",
    label: "Disable OOM Kill",
    description: "메모리 부족 시 OOM Killer 동작을 비활성화합니다.",
    category: "resource",
    type: "boolean",
  },
  {
    key: "oomScoreAdj",
    yamlKey: "oom_score_adj",
    label: "OOM Score Adj",
    description: "호스트 OOM 우선순위 값을 조정합니다.",
    category: "resource",
    type: "text",
    placeholder: "-500",
  },
  {
    key: "pidsLimit",
    yamlKey: "pids_limit",
    label: "PIDs Limit",
    description: "컨테이너에서 생성 가능한 프로세스 수를 제한합니다.",
    category: "resource",
    type: "text",
    placeholder: "100",
  },
  {
    key: "shmSize",
    yamlKey: "shm_size",
    label: "SHM Size",
    description: "컨테이너 /dev/shm 크기를 설정합니다.",
    category: "resource",
    type: "text",
    placeholder: "64m",
  },
  {
    key: "gpus",
    yamlKey: "gpus",
    label: "GPUs",
    description:
      "컨테이너에서 사용할 GPU 설정입니다.",
    category: "resource",
    type: "text",
    placeholder: "all",
  },
  {
    key: "blkioConfig",
    yamlKey: "blkio_config",
    label: "Block IO Config",
    description:
      "Block I/O 관련 기본 제한 값을 설정합니다.",
    category: "resource",
    type: "object",
    fields: [
      {
        key: "weight",
        yamlKey: "weight",
        label: "Weight",
        description: "Block I/O 가중치 값입니다.",
        type: "text",
        placeholder: "300",
      },
    ],
  },
  {
    key: "ulimits",
    yamlKey: "ulimits",
    label: "Ulimits",
    description:
      "컨테이너 ulimit 값을 설정합니다.",
    category: "resource",
    type: "object",
    fields: [
      {
        key: "nofile",
        yamlKey: "nofile",
        label: "Nofile",
        description: "열 수 있는 파일 수 제한입니다.",
        type: "object",
        fields: [
          {
            key: "soft",
            yamlKey: "soft",
            label: "Soft",
            type: "text",
            placeholder: "20000",
          },
          {
            key: "hard",
            yamlKey: "hard",
            label: "Hard",
            type: "text",
            placeholder: "40000",
          },
        ],
      },
      {
        key: "nproc",
        yamlKey: "nproc",
        label: "Nproc",
        description: "생성 가능한 프로세스 수 제한입니다.",
        type: "object",
        fields: [
          {
            key: "soft",
            yamlKey: "soft",
            label: "Soft",
            type: "text",
            placeholder: "20000",
          },
          {
            key: "hard",
            yamlKey: "hard",
            label: "Hard",
            type: "text",
            placeholder: "40000",
          },
        ],
      },
    ],
  },
]