// 보안/권한 설정 카테고리의 Compose service field definition을 관리합니다.
export const securityFields = [
  {
    key: "privileged",
    yamlKey: "privileged",
    label: "Privileged",
    description: "컨테이너를 privileged 모드로 실행합니다.",
    category: "security",
    type: "boolean",
  },
  {
    key: "capAdd",
    yamlKey: "cap_add",
    label: "Capabilities Add",
    description: "컨테이너에 추가할 Linux capability 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "NET_ADMIN",
  },
  {
    key: "capDrop",
    yamlKey: "cap_drop",
    label: "Capabilities Drop",
    description: "컨테이너에서 제거할 Linux capability 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "MKNOD",
  },
  {
    key: "cgroup",
    yamlKey: "cgroup",
    label: "Cgroup",
    description: "컨테이너의 cgroup namespace 모드를 설정합니다.",
    category: "security",
    type: "select",
    options: [
      { label: "선택 안 함", value: "" },
      { label: "host", value: "host" },
      { label: "private", value: "private" },
    ],
  },
  {
    key: "cgroupParent",
    yamlKey: "cgroup_parent",
    label: "Cgroup Parent",
    description: "컨테이너가 사용할 cgroup parent 값을 지정합니다.",
    category: "security",
    type: "text",
    placeholder: "m-executor-abcd",
  },
  {
    key: "devices",
    yamlKey: "devices",
    label: "Devices",
    description:
      "컨테이너에 연결할 host device 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "/dev/ttyUSB0:/dev/ttyUSB0",
  },
  {
    key: "deviceCgroupRules",
    yamlKey: "device_cgroup_rules",
    label: "Device Cgroup Rules",
    description: "컨테이너 device cgroup rule 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "c 1:3 mr",
  },
  {
    key: "groupAdd",
    yamlKey: "group_add",
    label: "Group Add",
    description: "컨테이너 프로세스에 추가할 group 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "1000",
  },
  {
    key: "ipc",
    yamlKey: "ipc",
    label: "IPC",
    description: "컨테이너 IPC namespace 모드를 설정합니다.",
    category: "security",
    type: "text",
    placeholder: "host",
  },
  {
    key: "isolation",
    yamlKey: "isolation",
    label: "Isolation",
    description: "컨테이너 isolation 기술을 지정합니다. 주로 Windows container에서 사용됩니다.",
    category: "security",
    type: "select",
    options: [
      { label: "선택 안 함", value: "" },
      { label: "default", value: "default" },
      { label: "process", value: "process" },
      { label: "hyperv", value: "hyperv" },
    ],
  },
  {
    key: "pid",
    yamlKey: "pid",
    label: "PID",
    description: "컨테이너 PID namespace 모드를 설정합니다.",
    category: "security",
    type: "text",
    placeholder: "host",
  },
  {
    key: "securityOpt",
    yamlKey: "security_opt",
    label: "Security Options",
    description: "컨테이너 보안 옵션 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "no-new-privileges:true",
  },
  {
    key: "sysctls",
    yamlKey: "sysctls",
    label: "Sysctls",
    description:
      "컨테이너 sysctl 설정 목록입니다.",
    category: "security",
    type: "list",
    placeholder: "net.core.somaxconn=1024",
  },
]